In [150]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_excel(r"D:/work hard/Pandas/data/Customer Call List.xlsx")
df

make another dataset, not change the main data set

In [ ]:
df_dup = df[df.duplicated()]
df_dup

In [ ]:
# df.drop_duplicates() # show change dataset
df = df.drop_duplicates()
df

Drop unuse column

In [154]:
df.drop(columns='Not_Useful_Column', inplace= True)
# Or
# df = df.drop(columns='Not_Useful_Column')

C:\Users\user\AppData\Local\Temp\ipykernel_8520\1672472582.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns='Not_Useful_Column', inplace= True)

In [ ]:
df

remove space, tabs, newline char

In [156]:
df['Last_Name'] = df["Last_Name"].str.strip("123./_")

C:\Users\user\AppData\Local\Temp\ipykernel_8520\2365075592.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Last_Name'] = df["Last_Name"].str.strip("123./_")

In [157]:
# df['First_Name'] = df['First_Name'].str.strip('1234/#$')

In [158]:
# df["Last_Name"] = df["Last_Name"].str.lstrip() # remove white space into this col in left
# df["Last_Name"] = df["Last_Name"].str.rstrip() # remove white space into this col in Right
# df["Last_Name"] = df["Last_Name"].str.lstrip('/')
# df["Last_Name"] = df["Last_Name"].str.lstrip('...')
# df["Last_Name"] = df["Last_Name"].str.rstrip('_')
# df

For phone number

In [ ]:
df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','', regex=True)
df

formate the number

In [ ]:
# df['Phone_Number'].apply(lambda x: x[0:3]+'-'+x[3:6]+'-'+x[6:])
df['Phone_Number']=df['Phone_Number'].astype('str').apply(lambda x: x[0:3]+'-'+x[3:6]+'-'+x[6:])

df

In [ ]:
df['Phone_Number']=df['Phone_Number'].str.replace('nan--|Na--', '', regex=True)
df

Work with Split

In [ ]:
df[['S_add', 'state', 'Zip_code']] = df['Address'].str.split(',',n = 2, expand=True)
df

when it contain more than one special case this time we are use this type of code

df[['Part1', 'Part2']] = df['Address'].str.extract(r'([^,_$]+)[,_$](.+)')

paying customer answer replace all in one line of code, and also change it separately

In [163]:
# df['Paying Customer'].str.replace('Yes', 'Y')
# df['Paying Customer'].str.replace('No', 'N')

In [ ]:
df['Paying Customer']=df['Paying Customer'].replace({'Yes': 'Y', 'No':'N'})
df

In [ ]:
df['Do_Not_Contact']=df['Do_Not_Contact'].replace({'Yes': 'Y', 'No':'N'})
df

Now replace hole dataframe specific values

In [166]:
df = df.replace('N/a', '') # this is change one value at a time

fill with null

In [170]:
df = df.replace('', pd.NA)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,S_add,state,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,White,<NA>,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,<NA>,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,<NA>,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,<NA>,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,<NA>,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,<NA>,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,<NA>,<NA>,<NA>,Y,<NA>,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

null fill with ''

In [168]:
# df = df.fillna('')
# df

Drop rows if ph_number contain null and do_not_cntact is Y

In [173]:
df = df[~(df['Phone_Number'].isna() | (df['Do_Not_Contact'] == 'Y'))]
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,S_add,state,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

set new index

In [176]:
df = df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,S_add,state,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
2,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
3,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
4,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
5,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
6,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
8,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
9,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None